_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 55
                - 71
                - 75
            "2":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 55
                - 71
                - 75
            "3":
                - 1
                - 2
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.16
            "5": 0.19.8
            "6": 4.49.0
            "8":
                - 5
            "12": 0.19.8
            "13": linux-x86_64
ALPHA:
    value: 2
BATCH_SIZE:
    value: 128
BETA:
    value: 1
CLIP_EPSILON:
    value: 0.15
COMPLETION_CHECK_STEPS:
    value: 20
COMPLETION_PROBABILITY:
    value: 0.3
DATASET_NAME:
    value: tatsu-lab/alpaca
DEVICE:
    value: cuda
ENTROPY_COEF:
    value: 0.02
EPISODE_LENGTH:
    value: 50
EVAL_EPISODES:
    value: 5
EVAL_INTERVAL:
    value: 15
FINAL_EVAL_EPISODES:
    value: 10
GAE_LAMBDA:
    value: 0.9
GAMMA:
    value: 0.95
HIDDEN_DIM:
    value: 512
INPUT_DIM:
    value: 512
LAMBDA:
    value: 5
LEARNING_RATE:
    value: 0.0001
LOG_INTERVAL:
    value: 5
MAX_EPISODES:
    value: 200
MAX_GRAD_NORM:
    value: 0.5
MAX_LENGTH:
    value: 100
MAX_LOAD_FACTOR:
    value: 1.5
MAX_SAMPLES:
    value: 1000
MODEL_ELO_SCORES:
    value:
        "0": 1200
        "1": 1100
MODEL_LATENCY_RANGES:
    value:
        default:
            - 0.6
            - 1.1
        gpt2:
            - 0.5
            - 1
        qwen:
            - 0.7
            - 1.2
MODEL_NAMES:
    value:
        - openai-community/gpt2
        - Qwen/Qwen2.5-0.5B
PLOT_INTERVAL:
    value: 50
PPO_EPOCHS:
    value: 6
SAVE_INTERVAL:
    value: 25
SERVER_CAPACITIES:
    value:
        - 8
        - 6
TEMPERATURE:
    value: 0.7
TIME_STEP:
    value: 0.1
VALUE_COEF:
    value: 0.25
WANDB_ENTITY:
    value: null
WANDB_PROJECT:
    value: enhanced-llm-router-ppo
